FROM maven:3.6.3-openjdk-8 AS MAVEN_BUILD

COPY ./ ./

RUN mvn clean package

FROM openjdk:8
EXPOSE 8761

COPY --from=MAVEN_BUILD /target/Discovery-Server.jar Discovery-Server.jar
ENTRYPOINT ["java", "-jar", "Discovery-Server.jar"]