logging:
   level:
      org:
         springframework:
            cloud:
               gateway: DEBUG



spring:
  application:
    name: Api-Gateway
  config:
    import: configserver:http://configserver:8181
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: '*'
            allowedOrigins: 'http://localhost:4200'
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: Product-Catalog-Service
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
            
        - id: Category-Service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/c/**
          filters:
            - RewritePath=/api/c/(?<segment>/?.*), /$\{segment}

        - id: Image-Service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/api/i/**
          filters:
            - RewritePath=/api/i/(?<segment>/?.*), /$\{segment}
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: false
    fetch-registry: true

server:
  port: 9020