FROM maven:3.6.3-openjdk-8 AS MAVEN_BUILD

COPY ./ ./

RUN mvn clean package

FROM openjdk:8

COPY --from=MAVEN_BUILD /target/Product-Catalog-Service.jar Product-Catalog-Service.jar
#COPY /target/Product-Catalog-Service.jar Product-Catalog-Service.jar

ENTRYPOINT ["java", "-jar", "Product-Catalog-Service.jar"]