FROM maven:3.6.3-openjdk-8 AS MAVEN_BUILD

COPY ./ ./

RUN mvn clean package

FROM openjdk:8

COPY --from=MAVEN_BUILD /target/Stock-Service.jar Stock-Service.jar

#COPY /target/Stock-Service.jar Stock-Service.jar

ENTRYPOINT ["java", "-jar", "Stock-Service.jar"]